config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root 'storefront#all_items'

  get 'storefront/all_items'

  get 'storefront/items_by_category'

  get 'storefront/items_by_brand'
  
  get 'categorical' => 'storefront#items_by_category'
  get 'branding' => 'storefront#items_by_brand'
  get 'all' => 'storefront#all_items'

  resources :products
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	belongs_to :category


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, :categories, :brands

  def categories
  	@categories = Category.all
  end

   def brands
  	@brands = Product.pluck(:brand).sort.uniq!
    if @brands == nil
        @brands = Product.pluck(:brand).sort
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 before_action :set_category, only: [:show, :edit, :update, :destroy]

 # GET /categories
 # GET /categories.json
 def index
   @categories = Category.all
 end

 # GET /categories/1
 # GET /categories/1.json
 def show
 end

 # GET /categories/new
 def new
   @category = Category.new
 end

 # GET /categories/1/edit
 def edit
 end

 # POST /categories
 # POST /categories.json
 def create
   @category = Category.new(category_params)

   respond_to do |format|
     if @category.save
       format.html { redirect_to @category, notice: 'Category was successfully created.' }
       format.json { render :show, status: :created, location: @category }
     else
       format.html { render :new }
       format.json { render json: @category.errors, status: :unprocessable_entity }
     end
   end
 end

 # PATCH/PUT /categories/1
 # PATCH/PUT /categories/1.json
 def update
   respond_to do |format|
     if @category.update(category_params)
       format.html { redirect_to @category, notice: 'Category was successfully updated.' }
       format.json { render :show, status: :ok, location: @category }
     else
       format.html { render :edit }
       format.json { render json: @category.errors, status: :unprocessable_entity }
     end
   end
 end

 # DELETE /categories/1
 # DELETE /categories/1.json
 def destroy
   @category.destroy
   respond_to do |format|
     format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
     format.json { head :no_content }
   end
 end

 private
   # Use callbacks to share common setup or constraints between actions.
   def set_category
     @category = Category.find(params[:id])
   end

   # Never trust parameters from the scary internet, only allow the white list through.
   def category_params
     params.require(:category).permit(:name)
   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :quantity, :description, :brand, :rating, :category_id, :image)
    end
end

app/controllers/storefront_controller.rb
class StorefrontController < ApplicationController
  
  def all_items
    @products = Product.all
  end

  def items_by_category
    @category = Category.find(params[:cat_id])
    @products = Product.all
    @products_by_cat = []

    @products.each do |product|
      if product.category.id == params[:cat_id].to_i
        @products_by_cat.push(product)
      end
    end
  end
 
  def items_by_brand
    @brand_name = params[:brand]
    @products = Product.all
    @products_by_brand = []

    @products.each do |product|
      if product.brand == params[:brand]
        @products_by_brand.push(product)
      end
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class = 'table'>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7css/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Products</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <% @categories.each do |cat| %>
                <li><%= link_to cat.name, categorical_path(cat_id: cat.id) %></li>
              <% end %>
          </ul>
        </li>

        <li>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Brands <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @brands.each do |brand| %>
              <li><%= link_to brand, branding_path(brand: brand) %>
              </li>
            <% end %>
          </ul>
      </li> 
         </li>
      </ul>
     
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li>
              <% if user_signed_in? %>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
              <% else %>
                <%= link_to "Sign In", root_path, class: "btn btn-primary" %>
              <% end %>
            </li>
            
            <li>
              <%= link_to "Sign Up", new_user_registration_path,  class: "btn btn-info" %>
            </li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  
<div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    <div class="pull-right">
    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <% end %>
     
  </div>
</footer>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.js"></script>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
 <% if @product.errors.any? %>
   <div id="error_explanation">
     <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

     <ul>
     <% @product.errors.full_messages.each do |message| %>
       <li><%= message %></li>
     <% end %>
     </ul>
   </div>
 <% end %>

 <div class="field">
   <%= f.label :name %><br>
   <%= f.text_field :name %>
 </div>
 <div class="field">
   <strong>Upload Product Image:</strong>
   <%= f.file_field :image %>
 </div>
 <div class="field">
   <%= f.label :price %><br>
   <%= f.text_field :price %>
 </div>
 <div class="field">
   <%= f.label :quantity %><br>
   <%= f.number_field :quantity %>
 </div>
 <div class="field">
   <%= f.label :description %><br>
   <%= f.text_area :description %>
 </div>
 <div class="field">
   <%= f.label :brand %><br>
   <%= f.text_field :brand %>
 </div>
 <div class="field">
   <%= f.select(:category_id, @categories.collect { |c| [c.name, c.id]}, {include_blank: "Please Select a Category"}) %>
 </div>
 <div class="actions">
   <%= f.submit %>
 </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class = 'table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Rating</th>
      <th>Category</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.rating %></td>
        <td><%= product.category.name%></td>
        <td><%= product.image%></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 
<%= link_to "New Product", new_product_path, class: "btn btn-default" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @product.rating %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category_id %>
</p>

<p>
 <image src="<%= @product.image %>"> 
 
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/storefront/all_items.html.erb
<h1>Welcome to our E-commerce Store</h1>

<div class="row">
   <% @products.each do |product| %>
   <div class="col-md-4">
       <div class="well center-it">
           <p><%= image_tag product.image.url, width: '90%' %></p>
           <h3><%= link_to product.name, product %></h3>
           <p><%= number_to_currency product.price %></p>
           <p>
               <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
                   <span class="glyphicon glyphicon-plus"> Quick Info </span>
               </a>
           </p>
       </div>
   </div>
   <div id="myModal_<%= product.id %>" class="modal fade" tabindex="-1" role="dialog">
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title"><%= link_to product.name, product %></h4>
     </div>
     <div class="modal-body">
           <p><%= number_to_currency product.price %></p>
            <p><%= product.description %></p>
     </div>
     <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       <button type="button" class="btn btn-primary">Save changes</button>
     </div>
   </div><!-- /.modal-content -->
 </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
   <% end %>
</div>

app/views/storefront/items_by_brand.html.erb
<h1><%= @brand %></h1>

<div class="row">
    <% @products_by_brand.each do |product| %>
    <div class="col-md-4">
        <div class="well center-it">
            <p><%= image_tag product.image.url, width: '100%' %></p>
            <h3><%= link_to product.name, product %></h3>
            <p><%= number_to_currency product.price %></p>
            <p>
			    <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
			        <span class="glyphicon glyphicon-plus"> quick info</span>
			    </a>
			</p>
        </div>
    </div>
    <div id="myModal_<%= product.id %>" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= link_to product.name, product %></h4>
      </div>
      <div class="modal-body">
            <p><%= number_to_currency product.price %></p>
             <p><%= product.description %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
    <% end %>

app/views/storefront/items_by_category.html.erb
<h1>All <%= @category.name %></h1>

<div class="row">
    <% @products_by_cat.each do |product| %>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div style="height:150px;">
                        <%= image_tag product.image.url(:thumb) %>
                    </div>
                    <p> <a href="#" data-toggle="modal" data-target="#myModal_<%= product.id %>">
                    <span class="glyphicon glyphicon-plus"> quick info</span>
                </a></p>
                <p><strong><%= number_to_currency product.price %></strong></p>
                <p><%= product.name %></p>
                <p>Made by: <%= product.description %></p>
                </div>
            </div>
        </div>
<div id="myModal_<%= product.id %>" class="modal fade" tabindex="-1" role="dialog">
 <div class="modal-dialog" role="document">
   <div class="modal-content">
     <div class="modal-header">
       <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <h4 class="modal-title"><%= link_to product.name, product %></h4>
     </div>
     <div class="modal-body">
           <p><%= number_to_currency product.price %></p>
            <p><%= product.description %></p>
     </div>
     <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       <button type="button" class="btn btn-primary">Save changes</button>
     </div>
   </div><!-- /.modal-content -->
 </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
   <% end %>

</div>